pr:
  branches:
    include:
      - dev
      - v*.x

trigger:
  branches:
    include:
      - dev
      - v*.x
  tags:
    include:
      - v*.*.*

variables:
  isTagTriggered: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  prefix: $[format('0.{0:yyyy}.{0:MMdd}', pipeline.startTime)]
  version: $[format('{0}.{1}', variables.prefix, counter(variables.prefix, 1))] # e.g. 0.2001.0203.4
  fileVersion: $[variables.version]

pool:
  name: 1ES-Hosted-AzFunc
  demands:
    - ImageOverride -equals MMS2022TLS

jobs:
  - job: buildExtension
    displayName: Build WebJobs extension
    variables:
      dropPath: $(System.ArtifactsDirectory)\azure-functions-rabbitmq-extension\net\$(version)
    steps:
      - powershell: | # Allow tags matching v1.2.3 and v1.2.3-xyz1
          $found = $(Build.SourceBranchName) | Select-String -Pattern '^v(\d+\.\d+\.\d+)(?:-\w+)*$'
          if (-not $found) {
            Write-Error "Found unexpected tag name: $(Build.ArtifactStagingDirectory)."
            exit 1
          }
          Write-Host "##vso[task.setvariable variable=version]$($found.Matches.Groups[1].Value)"
          Write-Host "##vso[task.setvariable variable=fileVersion]$($found.Matches.Groups[2].Value)"
        displayName: Extract version # e.g. 1.2.3
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))

      - task: UseDotNet@2
        displayName: Acquire .NET SDK
        inputs:
          packageType: sdk
          version: 6.x
          performMultiLevelLookup: true

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          arguments: --configuration Release -property:Version=$(fileVersion) -property:CommitHash=$(Build.SourceVersion)

      - task: DotNetCoreCLI@2
        displayName: Test extension
        inputs:
          command: test
          projects: test\WebJobs.Extensions.RabbitMQ.Tests\WebJobs.Extensions.RabbitMQ.Tests.csproj
          arguments: --configuration Debug

      - task: DotNetCoreCLI@2
        displayName: Pack extension
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))
        inputs:
          command: pack
          searchPatternPack: src\WebJobs.Extensions.RabbitMQ.csproj
          configurationToPack: Release
          buildProperties: Version=$(version);CommitHash=$(Build.SourceVersion)
          outputDir: $(dropPath)
          nobuild: true
          verbosityPack: minimal

      - task: ManifestGeneratorTask@0
        displayName: Generate SBOM manifest
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))
        inputs:
          buildDropPath: $(dropPath)
          packageName: Azure Functions RabbitMQ Extension
          packageVersion: $(version)

      - publish: $(Build.ArtifactStagingDirectory)
        displayName: Publish extension package
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))
        artifact: drops

  - job: buildJavaBindings
    displayName: Build Java library
    variables:
      dropPath: $(System.ArtifactsDirectory)\azure-functions-rabbitmq-extension\java\$(version)
    steps:
      - powershell: | # Allow tags matching v1.2.3 and v1.2.3-xyz1
          $found = $env:BUILD_SOURCEBRANCHNAME | Select-String -Pattern '^v(\d+\.\d+\.\d+)(?:-\w+)*$'
          if (-not $found) {
            Write-Error "Found unexpected tag name: $($env:BUILD_SOURCEBRANCHNAME)."
            exit 1
          }
          Write-Host "##vso[task.setvariable variable=version]$($found.Matches.Groups[1].Value)"
        displayName: Extract version # e.g. 1.2.3
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))

      - task: Maven@3
        displayName: Set library version
        inputs:
          mavenPomFile: binding-library\java\pom.xml
          goals: versions:set
          options: --define=newVersion=$(version)

      - task: Maven@3
        displayName: Build library
        inputs:
          mavenPomFile: binding-library\java\pom.xml
          options: --batch-mode --define=gpg.skip --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --update-snapshots

      - powershell: |
          $prefix = 'azure-functions-java-library-rabbitmq-$(version)'
          $source = 'binding-library\java'

          New-Item '$(dropPath)' -ItemType Directory
          Copy-Item "$source\pom.xml" "$(dropPath)\$prefix.pom"
          Copy-Item "$source\target\$prefix.jar" "$(dropPath)\$prefix.jar"
          Copy-Item "$source\target\$prefix-javadoc.jar" "$(dropPath)\$prefix-javadoc.jar"
          Copy-Item "$source\target\$prefix-sources.jar" "$(dropPath)\$prefix-sources.jar"
        displayName: Copy output files
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))

      - task: ManifestGeneratorTask@0
        displayName: Generate SBOM manifest
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))
        inputs:
          buildDropPath: $(dropPath)
          packageName: Azure Functions RabbitMQ Java Bindings
          packageVersion: $(version)

      - publish: $(Build.ArtifactStagingDirectory)
        displayName: Publish library package
        condition: and(succeeded(), eq(variables.isTagTriggered, 'True'))
        artifact: drops
